[General]

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""
Font="Open Sans"
FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

BackgroundPlaceholder=""
Background="Backgrounds/linh.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#2d2d2d"
DateTextColor="#2d2d2d"
TimeTextColor="#2d2d2d"

FormBackgroundColor="#ffffff"
BackgroundColor="#1e1e2e"
DimBackgroundColor="#000000"

LoginFieldBackgroundColor="#f5f5f5"
PasswordFieldBackgroundColor="#f5f5f5"
LoginFieldTextColor="#1e1e2e"
PasswordFieldTextColor="#1e1e2e"
UserIconColor="#555555"
PasswordIconColor="#555555"

PlaceholderTextColor="#888888"
WarningColor="#e74c3c"

LoginButtonTextColor="#ffffff"
LoginButtonBackgroundColor="#1e1e2e"
SystemButtonsIconsColor="#1e1e2e"
SessionButtonTextColor="#1e1e2e"
VirtualKeyboardButtonTextColor="#1e1e2e"

DropdownTextColor="#1e1e2e"
DropdownSelectedBackgroundColor="#e0e0e0"
DropdownBackgroundColor="#ffffff"

HighlightTextColor="#555555"
HighlightBackgroundColor="#e0e0e0"
HighlightBorderColor="#1e1e2e"

HoverUserIconColor="#1e1e2e"
HoverPasswordIconColor="#1e1e2e"
HoverSystemButtonsIconsColor="#1e1e2e"
HoverSessionButtonTextColor="#1e1e2e"
HoverVirtualKeyboardButtonTextColor="#1e1e2e"

PartialBlur=""
FullBlur=""
BlurMax=""
Blur=""
HaveFormBackground="false"
FormPosition="left"

VirtualKeyboardPosition="left"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
